### ISSUE TITLE
Build broken on mips, sparc

### ISSUE THREAD

**Issue by dkogan** [simsong/be13_api#6]
Hi.

Here's another issue uncovered by Debian's infrastructure: the
be13 source uses gcc intrinsics that don't have hardware
representations on some architectures. Example failure:

 https://buildd.debian.org/status/fetch.php?pkg=tcpflow&arch=mips&ver=1.4.0%2Brepack1-2&stamp=1384105930

Here we're trying to do __sync_add_and_fetch on a 64-bit
variable. This doesn't exist on MIPS. The problematic calls are
__sync_add_and_fetch() calls in

 plugin.cpp
 feature_recorder.cpp

One workaround is to convert these to 32-bit instead of 64-bit
variables. At least on MIPS this should suffice (I'm not sure
about others, like sparc). The variables in question are

 feature_recorder::file_number
 be13::plugin::dup_data_encountered
 scanner_params::sbuf::bufsize

Another workaround is to use plain lock-free C code. Do we really
need the atomicity? Please let me know if either of these
workarounds are reasonable.

Thanks
dima

**Comment by simsong** [comment]
Were you ever able to get access to the Debian porterbox? Is this still an issue?

**Comment by dkogan** [comment]
Simson L. Garfinkel <notifications@github.com> writes:

> Were you ever able to get access to the Debian porterbox? Is this
> still an issue?

I don't remember exactly what happened, but the builds now succeed on
all arches. I don't see any relevant patches I'm applying so presumably
you fixed it. You can close this bug, and thanks.

**Comment by simsong** [comment]
Oh great! Thanks.
